### ISSUE TITLE
iot.js doesn't work with iot.js code.

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjscode#109]
- JERRY_DEBUGGER_VERSION and JERRY_SNAPSHOT_VERSION have been changed. Could you update iot.js to be worked with iotjscode?

- Seemingly, iotjs code has been verified with the jerryscript executable, but not with the iot.js one. I'm worried that occasionally occurs. I've faced that at least three times so far. The iotjscode in the master branch should guarantee it works with iot.js in the master. Do you have any verification idea not to make this problem again?

**Comment by knightburton** [comment]
@daeyeon I've opened a PR in the iotjs to update the jerry.

**Comment by knightburton** [comment]
In the other hand, I do not know what should we do to guarantee that the iotjscode is works with the iotjs master. Maybe, we should enable, allow or implement new features after that the iotjs is ready to handle those.

**Comment by daeyeon** [comment]
@knightburton Thanks for the update pr.

Regarding the verification, how about adding the following step into the iotjscode travis checking? i) Cloning iot.js repo including the jerry submodule, ii) compare `JERRY_DEBUGGER_VERSION` in `./deps/jerry/jerry-core/debugger/debugger.h` with `JERRY_DEBUGGER_VERSION` in `src/app/client-debugger.js`. We might consider separating the version information from the files if they aren't proper places to be referred. 

Could you share your thought about this? I'm not sure if there is a better and easier way to achieve that.

**Comment by knightburton** [comment]
@daeyeon OK, that Idea seems good to me with a little change. I think that would be enough if we checkout only the necessary file, which contains the `JERRY_DEBUGGER_VERSION` information, not the whole project.

Also, I would like to ask that you want to do this only in the deployment or on the whole master branch?
