### ISSUE TITLE
Monaco editor.

### ISSUE THREAD

**Issue by knightburton** [Samsung/iotjscode#15]
The Monaco Editor is the code editor that powers VS Code.
I've checked the API and I think that the editor is capable of everything that we want to use: highlight, snippets, autocomplete etc. The ace editor has a much more customizable UI and a bit bigger funcionality for now but the monaco has better intellisens and management support (e.g.: Go to/Peek Definition or Command Palette). Also, if the debugger is want to support the VS Code in the future the similar IDE would be more user friendly. So, should we change the ace editor to the monaco? Any suggestion or comment are welcomed.

**Comment by daeyeon** [comment]
I prefer monaco. Since monaco editor has its counterpart on desktop, vscode, its users will feel more comfortable with iotjscode using monaco. Right-click context menu and command palette are a significant feature we can't find among any other editors. We can offer full features through it, and that will reduce many UI works. Plus, we once discussed a vscode extension for iot.js. So data of auto-completion for iot.js we write for monaco could be shared when vscode plugin is again considered.

However, although I prefer monaco. I think that we'd better finish the requirements and issues left based on Ace first. We need to set a milestone for October and see what requirements are, what's missing, issues, documentation, and so on.

**Comment by knightburton** [comment]
@daeyeon I've investigated a bit more about to change the ace to the monaco. I have some bad news for you. The monaco AMD module headers do not compatible with the webpack. After a little digging I've found a solution for this problem, you can check that over here (snippets from the webpack config and the main.js): https://gist.github.com/knightburton/cace94265c33b274c95ba400a4127d76
This workaround is a bit ugly and pain but this is working now for me in local, but it is not the best because with this solution there will be a weird script include in the index page.

According to a few issue in the monaco repository this is a major misisng part from the monaco for a while now.

My question is, what should we do whit this? Should we improve this workaround to work as good as possible or should we wait for some improve in the monaco?

**Comment by knightburton** [comment]
I've started to change the ace editor to monaco. I want to share the progress in this issue.

- [x] Remove the ace editor.
- [x] Init the monaco editor.
- [x ] Open file content.
- [x ] Remove file content.
- [x] Switch between contents.
- [x] Update file related functions in the Session module to adapt to the new Model based structure.
- [x] Highlight the currently executed line by the engine in the editor workspace.
- [x] Highlight the exceptional line in the editor workspace.
- [x] Add mosueClick logic to the monaco gutter line numbers to handle the breakpoint insert/delete.
- [x] Add contentChange logic to the monaco workspace to handle the available breakpoint marks.
- [x] Show the available breakpoint lines in the monaco gutter.
- [x] Add Breakpoint insert and delete logic to the available lines.
- [ ] Create a new autocompleter to display the available IoT.js functions in the intellisense context menu.
- [ ] Adapt the global theme settings to the monaco.
- [ ] Adapt the editor settings to the monaco.

**Comment by knightburton** [comment]
I've started to change the ace to monaco. I want to share the progress here.

- [x] Remove the ace editor.
- [x] Init the monaco editor.
- [x] Open file content.
- [x] Remove file content.
- [x] Switch between contents.
- [x] Update file related functions in the Session module to adapt to the new Model based structure.
- [x] Highlight the currently executed line by the engine in the editor workspace.
- [x] Highlight the exceptional line in the editor workspace.
- [x] Add mosueClick logic to the monaco gutter line numbers to handle the breakpoint insert/delete.
- [x] Add contentChange logic to the monaco workspace to handle the available breakpoint marks.
- [x] Show the available breakpoint lines in the monaco gutter.
- [x] Add Breakpoint insert and delete logic to the available lines.
- [ ] Adapt the source loader and reloader in the console panel to the monaco.
- [ ] Create a new autocompleter to display the available IoT.js functions in the intellisense context menu.
- [x] Adapt the global theme settings to the monaco.
- [ ] Adapt the editor settings to the monaco.
- [ ] Customize and check the style of the editor.
