### ISSUE TITLE
Regarding multimap module

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjscode#28]
Although https://github.com/Samsung/iotjscode/pull/27 is landed, we can further consider replacing the module itself with ES6 `Map`.

**Comment by knightburton** [comment]
Indeed, I support this idea!

**Comment by daeyeon** [comment]
Ok. I will do this once #20 is done.

**Comment by daeyeon** [comment]
In my second thoughts, this isn't much urgent for now, I'd like to close this and resume it later if much needed.
