### ISSUE TITLE
Rework the stylesheet for unique id selectors

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjscode#81]
https://github.com/Samsung/iotjscode/pull/3. We've once discussed `id` selector, but, for me, it still looks too far from the common CSS use.
How do you think to rework the stylesheet to get it to have unique ids?
There should be a way to retain the legibility with unique ids.

**Comment by knightburton** [comment]
Yes,  the scss file is a bit crowded for now. I have planned to rework that as soon as possible.
I have two proposal.
The first one is the regular, common way, use only the direct ids and the classes selectors.
Example:
```
/* Menu */
#menu { /* ... */ }
#one-menu-item { /* ... */ }
#one-toggle-button { /* ... */ }
#one-button-text{ /* ... */ }
.all-toggle-icon{ /* ... */ }
```

The second one is the nested style, if we want to keep the legibility with unique ids or classes:
Example:
```
/* Menu */
#menu {
  #one-menu-item {
    #one-toggle-button { /* ... */ }
    #one-button-text{ /* ... */ }
  }

  .all-togle-icon { /* ... */ }
}
```

The first one is easy to write and modify, the second one is more legibility and separated. I am fine with both solution, what do you think about these?

**Comment by daeyeon** [comment]
On my second thought, your second suggestion looks better. Plus, it would also be better to split one big scss into small pieces using `@import`.

**Comment by knightburton** [comment]
All right then, I will rework this based on these considerations, if its ok for you.

**Comment by knightburton** [comment]
The related PR is landed, I close this issue.
