### ISSUE TITLE
debugging in normal doesn't work

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjscode#97]
I observe the following error.

i) With the latest iot.js and iot.js Code, run `./iotjs -d any-js-module.js`
ii) Connect to the server

`The file "/path/any-js-module.js" is missing` pops up, and then, the debugger stops. It seems failed to decode the message sent from the server.

Can you clarify the above observation is right?

**Comment by knightburton** [comment]
What do you meand under `any-js-module.js`? Is that a builtin module, own  module or just a simple javascript file. However, It is works for me with the latest iotjs and iotjscode. After I synchronized the source in the iotjscode, I could debug the code.

**Comment by daeyeon** [comment]
@knightburton It's a simple javascript file. I checked this in another person's environment. Can you try this after updating npm modules also? I'm now in IRC for more queries.

**Comment by knightburton** [comment]
@daeyeon The #98 PR is solved your problem?

**Comment by daeyeon** [comment]
@knightburton Sorry for the belated response. We can close this issue. Thanks.
